# values.yaml

global:
  environment: production

indexerProxy:
  replicaCount: 2
  image:
    repository: your-repo/indexer-proxy
    tag: latest
  service:
    type: ClusterIP
    port: 80

coordinator:
  replicaCount: 1
  image:
    repository: your-repo/coordinator
    tag: latest
  service:
    type: ClusterIP
    port: 8000
  logLevel: "info"
  disableManagedProjects: true  # Tambahkan ini
  showStdoutInAdminUI: false    # Tambahkan ini
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

ipfs:
  replicaCount: 1
  image:
    repository: ipfs/go-ipfs
    tag: v0.9.1
  service:
    type: ClusterIP
    port: 5001
  persistence:
    enabled: true
    size: 10Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: subquery.example.com
      paths:
        - path: /
          pathType: Prefix