apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-subql-chart.fullname" . }}-coordinator
  labels:
    app.kubernetes.io/name: coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}