apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-subql-chart.fullname" . }}-ipfs
  labels:
    app.kubernetes.io/name: ipfs
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.ipfs.service.type }}
  ports:
    - port: {{ .Values.ipfs.service.port }}
      targetPort: 5001
      protocol: TCP
  selector:
    app.kubernetes.io/name: ipfs
    app.kubernetes.io/instance: {{ .Release.Name }}